# Generated by Django 5.1.3 on 2025-03-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskeventgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
