# Generated by Django 5.1.3 on 2024-11-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_alter_appointments_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='TasksEvents',
        ),
    ]
